export { default as SecretKeyWallet } from './secretkeyWallet'
export { default as KeystoreWallet } from './keystoreWallet'
export { default as Coin98Wallet } from './coin98Wallet'
export { default as PhantomWallet } from './phantomWallet'
export { default as SolletWallet } from './solletWallet'
export { default as SlopeWallet } from './slopeWallet'
